"""Add created_at & updated_at

Revision ID: 6d5ec596555c
Revises: 53d3f1354655
Create Date: 2023-05-02 17:20:27.788955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5ec596555c'
down_revision = '53d3f1354655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('date_updated')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('date_updated')

    # ### end Alembic commands ###
