"""Add unique key to role name

Revision ID: a33675f5387c
Revises: 6d5ec596555c
Create Date: 2023-05-02 17:25:38.549044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33675f5387c'
down_revision = '6d5ec596555c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_role_name', ['role_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint('unique_role_name', type_='unique')

    # ### end Alembic commands ###
